package main

import (
	"sample/pkg"
	// "sample/pkg/helpers"
	// "sample/pkg/module/sensorinfo"
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
	_ "sample/docs"
	// docs is generated by Swag CLI, you have to import it.
)

//	@title			Swagger datafabric API
//	@version		1.0
//	@description	datafabricThis is a sample server celler server.
//	@termsOfService	http://swagger.io/terms/datafabric

//	@contact.name	API Support datafabric
//	@contact.url	http://www.swagger.io/support.datafabric
//	@contact.email	support@swagger.io datafabric

//	@license.name	Apache 2.0
//	@license.url	http://www.apache.org/licenses/LICENSE-2.0.html

//	@host	localhost:8000

//	@securityDefinitions.basic	BasicAuth

// @externalDocs.description	OpenAPI
// @externalDocs.url			https://swagger.io/resources/open-api/
func main() {
	// if err, _ := helpers.InitPsql(); err != nil {
	// 	panic(err)
	// }
	// if err, _ := helpers.InitRedisConn(); err != nil {
	// 	panic(err)
	// }
	// if err := helpers.InitEnvSetting(); err != nil {
	// 	panic(err)
	// }

	router := gin.New()
	// 使用CORS中間件
	config := cors.DefaultConfig()
	config.AllowOrigins = []string{"*"} // 此處可以指定允許的來源，例如："http://localhost:8080"
	config.AllowMethods = []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"}
	router.Use(cors.New(config))

	router.Use(gin.Logger())
	pkg.SetRouter(router)

	router.GET("/", func(c *gin.Context) {
		c.JSON(200, gin.H{
			"success": true,
			"message": "service is running",
		})
	})
	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	router.Run(":8000")
}
